export const ADD_CART = 'add_cart'
export const REMOVE_CART = 'remove_cart'
export const PURCHASE = 'purchase'
export const GET_CART = 'get_cart'
export const GET_TOTAL = 'get_total'
export const GET_CATALOG = 'get_catalog'
