export const LOGIN = 'login'
export const GET_USUARIOS = 'get_usuarios'
export const ADD_USUARIO = 'add_usuario'
export const DELETE_USUARIO = 'delete_usuario'
export const EDIT_USUARIO = 'edit_usuario'
export const LOGOUT = 'logout'
